### ISSUE TITLE
error in Getting started chapter

### ISSUE THREAD

**Issue by christianmalek** [dmachat/angular-webpack-cookbook#1]
Hi,

In [Getting started](http://dmachat.github.io/angular-webpack-cookbook/Getting-started.html) you write the script `"build": "webpack"` in the `package.json` to use webpack with npm. But the `webpack.config.js` is located in the `build` dir. So how should this work? On my system it's only working if I move the webpack config in the project's root dir.

With `"build": "webpack --config config/webpack.config.js"` it works.

**Comment by dmachat** [comment]
Yeah, good point! I'll get your PR merged in shortly. Thanks!

**Comment by dmachat** [comment]
Merged and added to the wiki and gitbook.
